# This file contains example node parameters.
crossing_detection_node:
  ros__parameters:
    # Path of the debug image
    image_path: "resources/img/example.png"

    # Topics for an example publisher and subscriber
    image_topic: "/camera/undistorted"
    result_topic: "/example/result"
    debug_image_topic: "/example/debug_image"
